version: '3.8'

services:
  # (A) MongoDB 컨테이너
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  # (B) Danpyeonseon 크롤러
  danpyeonseon:
    build: .
    container_name: danpyeonseon-crawler
    depends_on:
      - mongo
    # -> Dockerfile CMD를 덮어써서,
    # -> build/libs/danpyeonseon-1.0-SNAPSHOT.jar 실행!
    command: ["java", "-jar", "build/libs/danpyeonseon-1.0-SNAPSHOT.jar"]

  # (C) Keyescape 크롤러
  keyescape:
    build: .
    container_name: keyescape-crawler
    depends_on:
      - mongo
    command: ["java", "-jar", "build/libs/keyescape-1.0-SNAPSHOT.jar"]

  # (D) Beatphobia 크롤러
  beatphobia:
    build: .
    container_name: beatphobia-crawler
    depends_on:
      - mongo
    command: ["java", "-jar", "build/libs/beatphobia-1.0-SNAPSHOT.jar"]

  # (E) eroom8 크롤러
  eroom8:
    build: .
    container_name: eroom8-crawler
    depends_on:
      - mongo
    command: [ "java", "-jar", "build/libs/eroom8-1.0-SNAPSHOT.jar" ]  # ✅ 올바른 경로

  # (F) 엑소더스이스케이프 크롤러
  exodus:
    build: .
    container_name: exodus-crawler
    depends_on:
      - mongo
    command: [ "java", "-jar", "build/libs/exodus-1.0-SNAPSHOT.jar" ]  # ✅ 올바른 경로

  # (G) 판타스트릭 크롤러
  fantastrick:
    build: .
    container_name: fantastrick-crawler
    depends_on:
      - mongo
    command: [ "java", "-jar", "build/libs/fantastrick-1.0-SNAPSHOT.jar" ]  # ✅ 올바른 경로

  # (H) 황금열쇠 크롤러
  goldenkey:
    build: .
    container_name: goldenkey-crawler
    depends_on:
      - mongo
    command: [ "java", "-jar", "build/libs/goldenkey-1.0-SNAPSHOT.jar" ]  # ✅ 올바른 경로

  # (I) 마스터키 크롤러
  masterkey:
    build: .
    container_name: masterkey-crawler
    depends_on:
      - mongo
    command: [ "java", "-jar", "build/libs/masterkey-1.0-SNAPSHOT.jar" ]  # ✅ 올바른 경로

  # (J) 쿠쿠룸 크롤러
  kukuroom:
    build: .
    container_name: kukuroom-crawler
    depends_on:
      - mongo
    command: [ "java", "-jar", "build/libs/kukuroom-1.0-SNAPSHOT.jar" ]  # ✅ 올바른 경로


  # (K) 쿠쿠룸 크롤러
  playtheworld:
    build: .
    container_name: playtheworld-crawler
    depends_on:
      - mongo
    command: [ "java", "-jar", "build/libs/playtheworld-1.0-SNAPSHOT.jar" ]  # ✅ 올바른 경로