version: '3.8'

services:
  # (A) MongoDB 컨테이너
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  # (B) 크롤러 공통 베이스 이미지 (한 번만 빌드됨)
  crawler-base:
    build: .
    image: crawler-base
    container_name: crawler-base
    environment:
      - JAR_FILE=""
    entrypoint: ["/bin/true"]  # 실행되지 않도록 설정

  # (C~O) 개별 크롤러 서비스 (공통 이미지 사용)
  danpyeonseon:
    image: crawler-base
    container_name: danpyeonseon-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=danpyeonseon-1.0-SNAPSHOT.jar
    restart: always

  keyescape:
    image: crawler-base
    container_name: keyescape-crawler
    environment:
      - JAR_FILE=keyescape-1.0-SNAPSHOT.jar
    restart: always

  beatphobia:
    image: crawler-base
    container_name: beatphobia-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=beatphobia-1.0-SNAPSHOT.jar
    restart: always

  eroom8:
    image: crawler-base
    container_name: eroom8-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=eroom8-1.0-SNAPSHOT.jar
    restart: always

  exodus:
    image: crawler-base
    container_name: exodus-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=exodus-1.0-SNAPSHOT.jar
    restart: always

  fantastrick:
    image: crawler-base
    container_name: fantastrick-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=fantastrick-1.0-SNAPSHOT.jar
    restart: always

  goldenkey:
    image: crawler-base
    container_name: goldenkey-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=goldenkey-1.0-SNAPSHOT.jar
    restart: always

  masterkey:
    image: crawler-base
    container_name: masterkey-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=masterkey-1.0-SNAPSHOT.jar
    restart: always

  kukuroom:
    image: crawler-base
    container_name: kukuroom-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=kukuroom-1.0-SNAPSHOT.jar
    restart: always

  playtheworld:
    image: crawler-base
    container_name: playtheworld-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=playtheworld-1.0-SNAPSHOT.jar
    restart: always

  pointnine:
    image: crawler-base
    container_name: pointnine-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=pointnine-1.0-SNAPSHOT.jar
    restart: always

  portraiteller:
    image: crawler-base
    container_name: portraiteller-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=portraiteller-1.0-SNAPSHOT.jar
    restart: always

  signescape:
    image: crawler-base
    container_name: signescape-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=signescape-1.0-SNAPSHOT.jar
    restart: always

  zeroworld:
    image: crawler-base
    container_name: zeroworld-crawler
    depends_on:
      - mongo
    environment:
      - JAR_FILE=zeroworld-1.0-SNAPSHOT.jar
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 259200000
